#!/usr/bin/env bash

function psgrep () {
	ps aux | grep "$1" | grep -v "grep"
}

function hsgrep () {
	history | grep "$1"
}

function mkcd () {
	mkdir -p "$1"
	cd "$1" || return
}

function mkopen () {
	mkdir -p "$(dirname "$1")"
	open "$1"
}
